### ISSUE TITLE
Remove bash requirement for MSVC Windows builds

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/KTX-Software#238]
Is it possible to remove the bash requirement for MSVC build on Windows? Just wanted to build toktx, and noticed it failing because there's a bash call as part of the project (looks like it's only required to generate some version number), which does seem to require additional steps to get things working.

Would it be possible to remove this requirement? A build setup that works out-of-the box on MSVC without the need for non-windows tools would make this much more useful.

On a side-note it would also be great if the CMake builds would support MSVC, instead of having explicit MSVC project files.

**Comment by MarkCallow** [comment]
Don't you use "Git for Windows"?

The CMake builds will support MSVC. Watch the `cmake` branch which is close to ready for merge. The current MSVC project files were generated by GYP and were provided as a service so users would not need to run GYP. All pre-generated projects will be removed when the `cmake` branch is merged.

**Comment by SaschaWillems** [comment]
Yes, I do use git on Windows, but I haven't installed the git bash tools.

Will check the CMake branch :)

**Comment by MarkCallow** [comment]
I am asking about the package called ["Git for Windows"](https://git-scm.com/download/win). Since it is the package provided by git-scm.com I expected that most people using Git on Windows would be using it. It includes MinGW and bash and I do not recall any option in its installer to not include MinGW & bash. The `cmake` branch is still using a bash script to generate  version identifiers. It defaults to the one in Git for Windows. We do not want to maintain 2 different scripts. We're happy to hear of an alternative way of implementing this that will allow a single script to work on Linux, macOS and Windows.

**Comment by SaschaWillems** [comment]
I do have git for Windows installed, but did not install/enable the gitbash integration as I'm using a different linux compatible terminal. But maybe that's so rare that it doesn't apply to most people? If so, feel free to close this issue.

The only other option I could think of would be using a python script, though that would add another dependency.

**Comment by MarkCallow** [comment]
With the CMake build, if CMake doesn't find bash itself you will be able to point it at your alternate linux compatible terminal for bash.

**Comment by SaschaWillems** [comment]
That's perfect. Just tested with the CMake branch, manually selected the bash binary and I was able to build the project out of the box. Closing this then.
