### ISSUE TITLE
No way to get number of loaded mipmap levels.

### ISSUE THREAD

**Issue by suikki** [KhronosGroup/KTX-Software#24]
Seems that there is no way to get the number of mipmap levels that were loaded from the file when using ktxLoadTexture\* functions. If a ktx-file does not contain full mipmap hierarchy I need to know how many levels there are, so I can set GL_TEXTURE_MAX_LEVEL correctly.

**Comment by msc-** [comment]
The loader already sets `GL_TEXTURE_MAX_LEVEL` when compiled for a version of OpenGL {,ES} that supports it, i.e. `GL_TEXTURE_MAX_LEVEL` is defined in gl.h. You can use `glGetTexParameter` to retrieve this value. Does this meet your need?

I can consider changing this to a run-time rather than compile time choice, based on whether the GL context supports the parameter. If the current support is insufficient, would this help?

**Comment by suikki** [comment]
Thanks. Seems that I was using some ancient version of libktx that didn't do that yet.

The only problem that I see is that I'm also building an OpenGL ES2 app on iOS. It supports max level with an extension where the same define is called TEXTURE_MAX_LEVEL_APPLE. So it would probably only work with a runtime check (or minor hacking).

**Comment by msc-** [comment]
I'll be happy to accept a pull request to make this work on iOS. I'm busy working on a KTX loader for Vulkan right now so I won't be able to look at this myself for a while.

**Comment by suikki** [comment]
Yeah, no problem. I already have the old version working with a minor hack and I'm also quite busy now so I won't be updating to the newer lib quite yet. But I'll probably do it at some point.

**Comment by MarkCallow** [comment]
This is fixed in the new API currently in incoming. The ktxTexture object created when loading a file has a field giving the number of mipmap levels in the file.
