### ISSUE TITLE
ktx to png

### ISSUE THREAD

**Issue by dhuy122** [KhronosGroup/KTX-Software#283]
I have a ktx file, please help me make it to png.
link: https://drive.google.com/file/d/1_RzZ9pyDXm8Tg6JWfvui38EzzxHoF6H0/view?usp=sharing

**Comment by MarkCallow** [comment]
If this is a ktx v1 file then please see  issue #36 for the anwser.

If this is a v2 file, there is as yet no easy way. If you can display the texture you can do a screen grab. If you don't mind building software, you can build the load tests from this repo and use gl3loadtests <your file> to display the texture. Whether gl3loadtests can display it depends on the format of the texture and what platform you are running on because the program does not contain any software decoders. It just loads the texture to OpenGL {,ES}.
