### ISSUE TITLE
Investigate transcoder performance drop

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Software#286]
The `msc_basis_transcoder` from the latest published release (4.0.0-beta3) is noticeably faster (avg. 15%) than the current repo state built with:
```
emcmake cmake -Bbuild-web-release . && cmake --build build-web-release --config Release
```

**Comment by MarkCallow** [comment]
@lexaknyazev how are you testing this?

The only change in the transcoder since v4.0.0-beta3 are we removed support for several target formats and then added back BC7 and ETC_EAC_RG11 ending up with ATC and PVRTC2 removed compared to beta3. I doubt this had any effect on speed.

A bug in the CMakeLists.txt was causing us to compile with -O3 instead of the intended -Oz was also fixed. This is the likely reason. -O3 is the option for best speed. -Oz "makes tradeoffs to reduce size". @lexaknyazev, please try -O3 and report back. On lines 84 & 85 of CMakeLists.txt, change -Oz to -O3.

**Comment by MarkCallow** [comment]
Compiling -O3 instead of -Oz increases the size of msc_basis_transcoder.wasm from 386k to 434k. The size of the msc_basis_transcoder.js remains the same at 61k.

libktx.wasm increases from 584k to 674k. libktx.js remains the same size at 181k.

I have not pushed a change to GitHub yet. @lexaknyazev please let me know if this brings performance back to the same level at 4.0.0-beta3.

**Comment by MarkCallow** [comment]
Does -O3 restore the performance? I want to create a new beta release so need the answer.

**Comment by lexaknyazev** [comment]
- `Oz` build is 10-15% slower than "beta3".
- `O3` build is about 2 times faster than "beta3".

**Comment by MarkCallow** [comment]
I'm unable to explain the 2nd data point. I'll go ahead and make `O3` the default.
