### ISSUE TITLE
toktx --bcmp --clevel 0 doesn't work properly

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/KTX-Software#287]
--clevel option claims to have a range 0-5, however the value `0` is equivalent to 1 because of this code:

```
        // Defaults to BASISU_DEFAULT_COMPRESSION_LEVEL
        if (params->compressionLevel)
            cparams.m_compression_level = params->compressionLevel;
```

Unsure how to fix this best since there appear to be multiple different ways to specify this (when using the library vs when using the command line tool), and I'm not sure if the expectation is that the caller should pass `1` explicitly, or not.

**Comment by MarkCallow** [comment]
Oops! We need to look at how to fix the API first. One possibility is to say there is no default; the caller must set the desired value, with a recommendation to use 1 as the base choice. Another is to require this parameter be initialized to -1 to get the default. The disadvantage to both of these is that callers will need more complex initialization of the struct than just `= { };` Unfortunately since this is a c API we can't provide an initializer that is automatically called.

Any other ideas, @zeux?

**Comment by MarkCallow** [comment]
Another possibility is to change the range to 1 to 6 with 0 still used to indicate the default should be used, which would be 2 in the new range. The disadvantage to this is that the range will differ from that of `basisu` tool. I'm leaning towards this fix.

All three have the further disadvantage that changes to applications will be required to get the same results as now.

**Comment by zeux** [comment]
Requiring explicit specification seems to be the cleanest route to me. Using a different range would be slightly problematic because this would mean that this parameter disagrees between basisu and toktx.

Wrt requiring extra work when filling the struct - it looks like that would only affect CompressBasisEx, not CompressBasis since that fills the struct by itself. Maybe this makes it acceptable?

**Comment by MarkCallow** [comment]
Yes, I thought the disagreement with `basisu` might be an issue. Okay, I'll go with requiring explicit specification. `CompressBasis`, `toktx` and `ktxsc` can continue to set 1 as the default. Only callers of `CompressBasisEx` will need to take any action.
