### ISSUE TITLE
Number of components returns unexpected value

### ISSUE THREAD

**Issue by atteneder** [KhronosGroup/KTX-Software#327]
On a --bcmp compressed ktx2 file of mine `ktxTexture2_GetNumComponents` returns 2.

Docs say:
> For Basis compressed textures, it will be the number of components in the image @e before encoding and deflation so it can be used to help choose a suitable transcode target format.

I'd expect 4 (=RGBA) in this case, 3 in most other cases (RGB without alpha).

Am I missing something?

Thanks for havinig a look!
Here's the files:

![alpha0](https://user-images.githubusercontent.com/2593014/95796142-68808380-0cec-11eb-9e2a-9ab8fa5b0b3e.png)
[alpha.ktx.zip](https://github.com/KhronosGroup/KTX-Software/files/5367951/alpha.ktx.zip)

**Comment by MarkCallow** [comment]
Very sorry. The documentation is out of date. We changed the DFD for ETC1S so that it has either 1 or 2 "samples" depending on whether there is just an RGB slice or an RGB slice and an alpha slice. The DFD's channel type(s) tell(s) you what is actually there. See section 3.10.2 in the [KTX specification](file:///Users/mark/Projects/khronos/github/KTX-Specification/out/index.html) for details.

Should I change `ktxTexture2_GetNumComponents` to decipher the channel type and return the actual number of components while adding a new function to return the number of "samples" found in the DFD or should I leave `ktxTexture2_GetNumComponents` as is and add a new function to return the channel types? The problem with the former is that the DFDs for block-compressed texture formats other than ETC1S and UASTC do not provide component information as it is not needed.

> I'd expect 4 (=RGBA) in this case, 3 in most other cases (RGB without alpha).

Note that if the alpha value for all texels is 1.0, the encoder will remove the alpha channel leaving an RGB texture.

**Comment by MarkCallow** [comment]
I've decided  to change `ktxTexture2_GetNumComponents` to return the actual number of components for uncompressed, ETC1S and UASTC compressed formats. For all others it will return the number of "samples" in the DFD which, for most of these formats, is 1 even though they will have 3 or 4 components when decompressed.

Comments?

**Comment by atteneder** [comment]
Thanks for clarifying!

I stumbled across this while trying to update my KTX wrapper for Unity and noticed that the format choice was wrong for transparent textures.

I looked at [webgl-demo.js](https://github.com/KhronosGroup/KTX-Software/blob/1978576717052f8b9808922af552c22872fb50bf/tests/webgl/libktx-webgl/webgl-demo.js#L382) as a reference:

> `formatString = ktexture.numComponents == 4 ? 'BC3' : 'BC1';`

I can't give a qualified recommendation as I don't know details of the DFD, but I try to help:

Will there ever be the need to get the detailed channel-type? If the answer is yes or uncertain, option two (add a new function to return the channel types) sounds more reasonable. I guess it would potentially return some sort of `Undefined` for non ETC1S/UASTC.

From a library user's perspective, solution 1 sounds easier to grasp/implement though.

hth

P.S. Haha, I quickly created this test texture a while ago. Thanks :)
