### ISSUE TITLE
Add make option for running tests

### ISSUE THREAD

**Issue by ErixenCruz** [KhronosGroup/KTX-Software#330]
We are incorporating libktx as a submodule in our repo. We already add gtests as another submodule, so when KTX-Software builds, it tries to add gtests again even though it already exists. gtests is only needed for running unit tests. Would it be possible to add an option in `CMakeLists.txt` for running tests. Something like adding a condition around the tests here: https://github.com/KhronosGroup/KTX-Software/blob/58c8e9818610fe20f3dd15b21e9b3cee7b8d4cc2/CMakeLists.txt#L547-L549

For example:
```
if(KTX_TESTS)
    add_subdirectory(tests)
endif()
```
CC @lilleyse @pjcozzi

**Comment by MarkCallow** [comment]
@atteneder please comment.

**Comment by atteneder** [comment]
Yeah, that makes total sense!

**Comment by atteneder** [comment]
Full thoughts:

Using the global `BUILD_TESTING` flag isn't sufficient, as you might want to disable just the KTX tests (not all).

It would be possible, I guess, to enable all tests by letting the outside configuration provide an external gtest target to link against. But I think hardly anyone needs that and it would grow the cmake config, so I don't support that.

Another solution would be to restructure the whole project, so that the pure `ktx` library is in a dedicated sub-folder, separate from tests and the test apps. CMake users might add this specific sub-directory only and don't worry about the rest. But that's some extra work and I'm not certain if it has downsides. So far I kept the structure as is.

The proposed change is a clean and fast solution. I'd approve a PR!

**Comment by MarkCallow** [comment]
@ErixenCruz please make a PR with this change.

> Another solution would be to restructure the whole project, so that the pure ktx library is in a dedicated sub-folder, separate from tests and the test apps. CMake users might add this specific sub-directory only and don't worry about the rest. But that's some extra work and I'm not certain if it has downsides. So far I kept the structure as is.

FWIW the Gyp-based builds generated a separate libktx project which was used by both the tests and tools projects. The downside was that you could not have both tests and tools projects open at the same time because the common libktx project could only be open in one of them.

**Comment by ErixenCruz** [comment]
Thank you very much @MarkCallow @atteneder
