### ISSUE TITLE
Expose vk format to gl formats functions

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/KTX-Software#337]
Some engines like Qt3D expect OpenGL enums for creating textures. Functions like glGetInternalFormatFromVkFormat are very useful, but they are not exposed as public API. Is it possible to expose them in ktx.h?

**Comment by MarkCallow** [comment]
Please use the [format switches generator](https://github.com/KhronosGroup/KTX-Specification/blob/main/generate_format_switches.rb) in the KTX-Specification repo to generate the body of a switch statement for mapping from Vulkan VkFormat enums to equivalent OpenGL enums. This is guaranteed to be spec compliant as it uses the same JSON database as the mappings given in the spec.

`glGetInternalFormatFromVkFormat` will not be exposed in libktx because it will be replaced by output from the above mentioned generator and for several other reasons.
