### ISSUE TITLE
Support for 3D textures above 4gb

### ISSUE THREAD

**Issue by georgeouzou** [KhronosGroup/KTX-Software#35]
Is there any way KTX can support 3d textures with mipmaps
with total size exceeding 4gb?

**Comment by msc-** [comment]
There is nothing limiting the total size of a KTX file, except the file system on which it resides. Each mip level is limited to 4GB though due to the 32-bit "imageSize" field that gives the level's size. Do you need mip levels larger than 4GB? Note that here a level's size includes all array layers and all faces.

**Comment by georgeouzou** [comment]
Yes the base 3d image (mip level) is above 4gb in size. The rest of the KTX file format fields can support this easily, but the 32-bit "imageSize" field cannot.

**Comment by msc-** [comment]
Good to know. I'll keep it in mind for the next version of the KTX format.

**Comment by MarkCallow** [comment]
KTX2 supports mip levels > 4GB. KTX never will.

**Comment by georgeouzou** [comment]
Ok thank you!
