### ISSUE TITLE
Invalid data in JPEG file. jpgd_status code: Success

### ISSUE THREAD

**Issue by arpu** [KhronosGroup/KTX-Software#373]
Hello, testing with nasa jpg from mars :>

toktx: failed to create image fromPIA2464-Perseverance_Sol3_Mastcam-Z_panorama.jpg. Invalid data in JPEG file. jpgd_status code: Success
the jpg is from https://mars.nasa.gov/resources/25640/mastcam-zs-first-360-degree-panorama/
51.8MB 

loads fine in browser https://mars.nasa.gov/system/resources/deepzooms/25640_PIA2464-Perseverance_Sol3_Mastcam-Z_panorama.jpg

ktx-software master a5a812ec2eabd2849cb81bccff5923023729bc42

**Comment by MarkCallow** [comment]
The issue here is that the width of the image is greater than a maximum (32768) set in the decoder I am using. I am reaching out to the author of the decoder to ask why the maximums have been set. There is also a minor problem with the error reporting which is why you got `jpgd_status code: Success`.

Many GPUs have texture size limits of 16,384 x 16,384. I expect some may support 32,768. Even if the decoder is fixed so the file can be read, the image will have to be resampled to create a texture within the GPU limits. What behavior would you like to see from `toktx` in this case? I think `toktx` should exit with an error if no `--resize` or `--scale` option is specified and the size is greater than 16,384 and it should issue a warning if the size is > 16,384 after a `--resize` or `--scale`. I do not think it should automatically resize. Some users may want to resize to a different size.

**Comment by arpu** [comment]
Hey,

tested with latest github master and looks good now
```toktx: failed to create image from /home/arpu/Downloads/25640_PIA2464-Perseverance_Sol3_Mastcam-Z_panorama.jpg. Invalid data in JPEG file. jpgd_status code: -249
``
i get the error, would be nice to show more info/warning for --resize/--scale, if the texture size  is to big.
i think this can be closed now
