### ISSUE TITLE
ktxHashTable_Deserialize does not respect endianness

### ISSUE THREAD

**Issue by greatgoogleymoogley** [KhronosGroup/KTX-Software#40]
lib/hashtable.c:316 just uses a cast to read the key value size which will be wrong if the source file uses opposite endianness. The deserialise function needs a parameter to specify endianness.

**Comment by MarkCallow** [comment]
Thanks for the report. Fixed in master (PR #48) and incoming (PR #49).

It is fixed by having the functions that read and return key-value data byte swap the key+value lengths, if necessary, before returning the data. This avoids an incompatible change with the existing API. It also avoids exposing outside the API whether or not swapping is needed.

You might be asking "what about metadata with binary values". At present none is defined in the spec.  In the event of someone defining their own, the spec says  _It is up to the vendor defining the key to specify how those bytes are to be interpreted (including the endianness of any encoded numbers)._
