### ISSUE TITLE
Replace GYP with CMake

### ISSUE THREAD

**Issue by bradc6** [KhronosGroup/KTX-Software#44]
I'm currently using libktx a sample app and want to integrate libktx into it. My project uses one cmake script for all platforms/configurations. I've started refactoring it pretty heavily @ https://github.com/bradc6/KTX/tree/refactor/cmake  (or more specifically https://github.com/bradc6/KTX/blob/refactor/cmake/build/cmake/linux/Debug/CMakeLists.txt)

I'm opening this issue to see if there is any interest in completing this 100% and making a pull request.

Thanks,
-Brad

**Comment by msc-** [comment]
`build/cmake/linux/{Debug,Release}/CMakeLists.txt` are generated by GYP from the various `.gyp` and `.gypi` files specifically for Linux. It should not be hand edited.

That said, I am interested in replacing gyp with cmake as the reasons I originally chose gyp no longer hold and Google has stopped supporting it. This would replace all the `.gyp` & `.gypi` files with one or more CMakeLists.txt files which should probably be in the project root directory, definitely not in the build directory.  There are 3 projects ktxtests, ktxtools and libktx. I say "one or more" because I am interested in providing Linux distribution packages for ktxtools and libktx and that might require separate CMakeLists.txt for each. I do not know. I have no familiarity with creating distribution packages and limited familiarity with cmake.

**Comment by AbandonedCart** [comment]
The entire setup for trying to run this project on Mac was far more complicated than necessary because of the gyp files and how little material is readily available about non-node gyp.

**Comment by MarkCallow** [comment]
@AbandonedCart, did the included xcode projects (build/xcode/{mac,ios}) not work for you? If not what was the issue? I build on the Mac all the time. The .xcodeproj files were generated from the gyp files via `make xcode` in the project root.

**Comment by AbandonedCart** [comment]
@MarkCallow Much in the same way I do not like to settle for downloading the compiled binary of something to resolve issues building the source, I would not call the `.xcodeproj` working a solution for the `.gyp` files being difficult. 

> I am interested in replacing gyp with cmake as the reasons I originally chose gyp no longer hold and Google has stopped supporting it.

I think this is a good idea. The `.gyp` files add unnecessary difficulty due to the lack of available support for them. 

Hopefully that better explains the purpose of my original post.

**Comment by MarkCallow** [comment]
@AbandonedCart, so your main point is to support replacing gyp with cmake. Thanks for the vote.

> Much in the same way I do not like to settle for downloading the compiled binary of something to resolve issues building the source

Did you have issues with `make xcode`?

**Comment by AbandonedCart** [comment]
It failed for the missing gyp. After a lot of stumbling around trying to figure out if it was something that should have been there or something I needed to install, I ended up finding out how travis handles it and doing that. It seemed to work fine after that.

**Comment by UX3D-schmithuesen** [comment]
@bradc6 @MarkCallow 
Has there been any progress on this? We are currently integrating KTX2 with https://github.com/KhronosGroup/glTF-Compressonator and a regular CMake setup would be helpful. @UX3D-wahlster @UX3D-kanzler

**Comment by MarkCallow** [comment]
There has been no progress on my end. I keep hoping for a volunteer who knows cmake well to step up.

And a note for anyone who stumbles on this thread who is having a problem, like @AbandonedCart  with the missing gyp, there are pointers to both GYP and instructions for installing it in the file BUILDING.md in this repo.

**Comment by atteneder** [comment]
I want to load KTX files within Unity3D (editor and runtime)
With the existing build tools it's not easy to quickly integrate the library though, especially since I only need the KTX loading/transcoding part.

So I forked this repo and created my own [CMake configuration](https://github.com/atteneder/KTX-Software/tree/cmake) (plus some C wrapping code) for this purpose only. It will be used in my [Texture loading Unity package](https://github.com/atteneder/BasisUniversalUnity)

**Comment by MarkCallow** [comment]
Thanks for letting us know @atteneder. Hopefully someone can turn it into a more general CMake configuration.

**Comment by MarkCallow** [comment]
@atteneder why is it easier to integrate the library within Unity with a CMake configuration? I know very little about CMake.

**Comment by atteneder** [comment]
> @atteneder why is it easier to integrate the library within Unity with a CMake configuration? I know very little about CMake.

It's less about CMake, that just happens to be the build tool I'm familiar with. What I needed:

1. Unity (on macOS) needs native libraries to be in .bundle format (dynamic libs are usually .dynlib files, just like the GYP Xcode project delivers)
2. To make integrating into C# Unity code easier, I like to create a small C wrapper around the KTX functions I need.
3. The library binary should be small/stripped to just the things I need.

To achieve this I thought were 3 options:
1. Learn GYP and tweak it => did not want to since that takes time and GYP does not seem vital anymore
2. Alter the GYP generated projects (Xcode, cmake, etc.) manually and repeat this everytime they are updated in the future => sounds like a lot of work long/mid-term
3. Create a new tailor-made CMake configuration

So, option 3 won out.

I may try to add the missing targets (especially the ktxtools) once I've got some time for it.

**Comment by UX3D-wahlster** [comment]
A general CMake list that works out of the box would be much appreciated. Right now libktx is not convenient to integrate in other (CMake) projects.

**Comment by MarkCallow** [comment]
@atteneder could you provide a PR with the changes to limit the library to reading, transcoding and uploading? It's something in the TODO list. If I get a PR you won't have to apply that change in future pulls.

**Comment by atteneder** [comment]
> @atteneder could you provide a PR with the changes to limit the library to reading, transcoding and uploading? It's something in the TODO list. If I get a PR you won't have to apply that change in future pulls.

Sure. I'll try to do it today/tomorrow.

**Comment by MarkCallow** [comment]
Thanks to @atteneder, there is now a CMake build system.
