### ISSUE TITLE
Resources utilization - High CPU consumption

### ISSUE THREAD

**Issue by juber-ivre** [KhronosGroup/KTX-Software#442]
I have the toktx running on an internal file system conversion. At the moment converting pngs and jpgs. Some of those files can reach  around 80mb in size. I'm passing the options below when converting and for the majority of files it works fine but having a closer look on CPU utilization I saw it maxing it out 6 cores as per screenshot below.

Is there any options I could pass to avoid it bar from --threads?
Is there any other options for large files conversion?

toktx --lower_left_maps_to_s0t0 --bcmp --srgb --genmipmap 

![image](https://user-images.githubusercontent.com/48788224/122578292-a5570400-d04b-11eb-9f4e-d32aa1d2b703.png)

**Comment by MarkCallow** [comment]
`--threads` is the only control. You can specify whatever limit you like up to the number if cores you have. It defaults to the value returned by `thread::hardware_concurrency()` which seems like it must be returning 6 in your case. Only the Basis Universal encoders explicitly use threads and parallel processing. You are selecting the ETC1S/BasisLZ encoder with the `--bcmp` option so `--threads` gives you the desired control.

There aren't any specific options for large file conversion ("encoding" is more accurate since you've specified `--bcmp`). You can twiddle the quality knobs to balance quality and encoding time as described in the documentation for `ktxBasisParams`.
