### ISSUE TITLE
Remove BasisParams separateRGToRGB_A; add option to generate 2 component normal map

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#455]
`separateRGToRGB_A` in `ktxBasisParams` isn't actually doing anything (a bug). We should remove it  and replace it with an option that takes as input a three component linear LDR normal map storing unit length normals as (R=X, G=Y, B=Z) and converts it to a two component X+Y normal map stored as (RGB=X, A=Y) before encoding to ETC1S or UASTC or any other encoder we might add in future.

@lexaknyazev what do you think?

**Comment by thokra1** [comment]
During integration of libktx into our asset pipeline, I noticed the same bug. The explicitly stated and semantically equivalent swizzle (i.e. RRRG), however, works as intended.

As for the option that handles swizzling automatically, [astcenc does this](https://github.com/ARM-software/astc-encoder/blob/main/Docs/Encoding.md#encoding-non-correlated-channels) as soon as one specifies the `-normal`.

So both approaches are used in practice and the only question is whether to take control over this away from the user.

**Comment by MarkCallow** [comment]
> take control over this away from the user.

Control over what? Since you can do with `--input_swizzle` what  `--separateRGToRGB_A` was supposed to do, reeplacing it doesn't take any control away.

> As for the option that handles swizzling to RRRG implicitly, astcenc does this as soon as one specifies the -normal option.

It does more than swizzle. Assuming the 3-component image provided as input contains unit normals, it converts to 2 component normals putting X in the R channels and Y in the alpha channel. This seems to me a useful function that should be provided for the BasisU encoders as well as I noted in my opening comment here.

**Comment by thokra1** [comment]
I think there's a little misunderstanding here. All I'm saying is that **BasisU** doesn't imply _any_ swizzling just because you tell the encoder to tweak for RG compression with the `-normal_map` option. **astcenc's**  `-normal` does (there is no need to specify a pre-compression swizzle with `-esw`, since `-normal` overwrites the mask anyway).

If you're not going for (U)ASTC/ETC1S in the first place, there might not be any need (or would be wrong) to swizzle to RRRG in the first place. For instance, going directly to BC5 with **bc7enc** does not require any pre-swizzled input (in fact, handing it anything that's not an RGB(A) input messes up the result, even grayscale RG PNGs but that's another story ...). Might not be true for all BCn compressors tho ...

So, if you're only targeting (U)ASTC or ETC1S, doing an implicit conversion from RGB(A) to RRRG is reasonable - when also adding a BCn compressor in the future, it might not be. 

I think it's best go BasisU's way and leave formatting of input data to the user. Instead, provide documentation on the requirements for proper normal map compression for every supported compressor.

**Comment by MarkCallow** [comment]
`toktx`'s current `--normal_mode` is a placeholder which I plan to change before the next release. I am thinking of separate options for 3- to 2-component normal map conversion, and for telling the encoder to optimize for normal maps along with the current `--input_swizzle`. Currently only the ASTC encoder optimizes for angular error. BasisU etc1s turns off RDO, uastc does nothing since its RDO is separately controlled and is off by default. I hope to support 3- to 2-component conversion for any relevant encoder.

However if 3- to 2-component conversion is specified and the output format is a 4-component block-compressed format, toktx/libktx will continue to separate the 2 components into RGB & A as it is the only rational way to handle 2 uncorrelated channels.

Note that the KTX specification places requirements on swizzling of 1- and 2-component inputs for interoperability.

By the way, the actual purpose of `basisu`'s `-separate_rg_to_color_alpha` is to separate those channels when the input has 3 or 4 components. As you've noted, Rich's BasisU and bc7 encoders all require 4-component inputs. When the input file has 2 components the PNG loader used by BasisU swizzles 'GREY' into the r, g & b channels and 'ALPHA' into the alpha channel to make the 4-component input which is exactly what toktx/libktx does.
