### ISSUE TITLE
Having trouble getting my dependencies up-to-date on debian 9

### ISSUE THREAD

**Issue by bennlich** [KhronosGroup/KTX-Software#458]
Hey there. I'm trying to install KTX-Software but getting stuck on some out of date libs. I wonder if debian 9 is too old for this project? I've never run into this problem before.

After installing the 4.0 .deb release of KTX-Software:

```
toktx --version
toktx: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by toktx)
toktx: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libktx.so.4)
```

then:

```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
```

ends in `GLIBCXX_3.4.25`

and:

```
strings /lib/x86_64-linux-gnu/libm.so.6 | grep GLIBC
```

ends in `GLIBC_2.28`.

So I have the libs, but I'm a minor version behind what is needed. `apt` tells me I'm up to date, so I'm not sure what to do next.

I tried building from source, but:

```
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
  CMake 3.15 or higher is required.  You are running version 3.13.4
```

Any help greatly appreciated! I'd love to try out these tools.

**Comment by MarkCallow** [comment]
KTX-Software needs CMake 3.15 so to build from source you will have to install an updated CMake on your Debian system. This might not be possible. I once tried to install a recent CMake from KitWare on Debian "Buster" - I don't know the mapping between names and numbers for Debian versions - but it proved impossible because it had a dependency on a version of libssl not in Buster.

The `.deb` release is built by our CI on Ubuntu 20.04 "Focal Fossa". Presumably the glibc dependencies come from there. Because of needing CMake 3.15 we cannot easily use the only other Ubuntu available in our CI (18.04 - Bionic) and I don't know if doing so would solve your issue.

Try updating your CMake or your version of Debian.

I'm surprised `apt` didn't flag the missing dependencies during install.
