### ISSUE TITLE
Memory leak with uastc

### ISSUE THREAD

**Issue by skaarj1989** [KhronosGroup/KTX-Software#465]
Lastest version (master)

```
Dumping objects ->
{55897} normal block at 0x0000010FFCBA4860, 24 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 10 00 00 00 00 00 
```

```cpp
ktxTexture *tex;
ktxTexture_CreateFromMemory(
    buffer, length, KTX_TEXTURE_CREATE_LOAD_IMAGE_DATA_BIT, &tex);

if (ktxTexture_NeedsTranscoding(tex)) {
  result = ktxTexture2_TranscodeBasis(reinterpret_cast<ktxTexture2 *>(tex),
                                      KTX_TTF_RGBA32, 0);
}

// ... loading to gpu

ktxTexture_Destroy(tex);
```

https://drive.google.com/file/d/1Op0nDvdIfW6tJP5XVuSuHnZ3JvNenrza/view?usp=sharing

Image converted with `toktx`
`--uastc 4 --uastc_rdo_l .5 --uastc_rdo_d 65536 --zcmp 22`

`--bcmp` is ok, no leaks

**Comment by MarkCallow** [comment]
When is `Dumping objects` happening. If at program exit, how can you be sure the leak is in `ktxTexture2_TranscodeBasis`, as you seem to be indicating, and not in your load for loading to gpu? Can you narrow down the location of the leak?

**Comment by skaarj1989** [comment]
1. `Dumping objects` happens at exit.
2. Leaks occurs ONLY with `--uastc` compressed images (when `ktxTexture2_TranscodeBasis` is involved).

**Comment by MarkCallow** [comment]
Which version of the software are you using? On Mac the allocator diagnostics are showing any leaks with the latest version of the software.

The example in your most recent comment does not show a call to ktxTexture2_TranscodeBasis. Is that intentional?

The texture you posted has `levelCount` == 0 which tells the loader to generate mipmaps. Depending on the transcode target format and the OpenGL or Vulkan implementation you are using, this may not be possible and the upload will fail. In my case I'm transcoding to BC3. My Vulkan implementation can't generate mipmaps for that format. Somewhat to my surprise as BC3 is a block-compressed format, my OpenGL implementation can.

**Comment by skaarj1989** [comment]
> Which version of the software are you using?

`master` on Windows

> The example in your most recent comment does not show a call to ktxTexture2_TranscodeBasis. Is that intentional?

Yes, it looks like `ktxTexture2_TranscodeBasis` is not to blame.

That code is actual minimal reproduction for the memory leak - just create and destroy.
