### ISSUE TITLE
CMake: rely on CMAKE_SYSTEM_PROCESSOR

### ISSUE THREAD

**Issue by SpaceIm** [KhronosGroup/KTX-Software#499]
Custom CMake function `set_target_processor_type()` is too fragile when cross-building, ktx should rely on `CMAKE_SYSTEM_PROCESSOR` variable (https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html), otherwise it could try to enable SSE for architectures without SSE support when cross-building.

Basically, cross-build from macOS x86_64 to macOS M1 is broken currently if `BASISU_SUPPORT_SSE` is not turned OFF explicitly.

**Comment by MarkCallow** [comment]
I thought that `CMAKE_SYSTEM_PROCESSOR` was the processor the build was running on. We need the target processor. At the time I created `set_target_processor_type()` I couldn't find any suitable CMake variable. Is `set_target_processor_type()` not detecting arm64 when you are configuring to build for an M1 mac?

In any case the whole thing is a kludge. The proper fix is for the source code to determine what, if any, SIMD instruction set it can use from compiler pre-defined macros. In a universal binary build scenario we cannot use -D macros.

**Comment by SpaceIm** [comment]
> I thought that CMAKE_SYSTEM_PROCESSOR was the processor the build was running on

Yes and No. For native build yes (but it's fine), for cross-build it's not defined and consumers are supposed to set it explicitly through a toolchain file for example, it's the recommended way to use CMake: https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html

> Is set_target_processor_type() not detecting arm64 when you are configuring to build for an M1 mac?

Not if I cross-build from x86_64 to M1

**Comment by MarkCallow** [comment]
Please post the command you are using to configure your build.

**Comment by MarkCallow** [comment]
If I set `CMAKE_OSX_ARCHITECTURES` to arm64 and do not set `BASISU_SUPPORT_SSE` then an M1 cross build on my x86_64 works. The only way I get the failure you describe is if I set `BASISU_SUPPORT_SSE` when running CMake's configure step. I inadvertently did this because I had it set in the M1 preset in my CMakeUserPresets.json. This was due to copy/paste from the x86_64 preset. After deleting it, the build is fine.

The project's CMakeLists.txt only adds the `BASISU_SUPPORT_SSE` option to the cache when the processor is x86_64 but it doesn't do anything should the option exist due to it being set on the configure command line or in user presets leading to your build error. Using a toolchain file will not fix this problem.

I can make configure more robust by adding

```
unset(BASISU_SUPPORT_SSE CACHE)
```

and print a warning if the processor is not x86_64 and it is set What do you think?

**Comment by MarkCallow** [comment]
`unset` doesn't work. I've had to force set `BASISU_SUPPORT_SSE` off. See the commit referenced above.

**Comment by MarkCallow** [comment]
The PR now fixes this by using CMAKE_DEPENDENT_OPTION. Much simpler.
