### ISSUE TITLE
"Possible loss of data" warnings in Java wrapper

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#547]
Visual Studio is flagging several "Possible loss of data" warnings in the Java wrapper. See https://ci.appveyor.com/project/msc-/ktx/build/job/0waa6qs3oyh9jvmv for example.

These relate to passing `ktx_size_t` back to Java as jsize or jint. ktx_size_t is 64-bit. @ShukantPal is there a 64-bit Java data type we can use instead. Please submit a PR either with a change to 64-bit types, if so.

**Comment by ShukantPal** [comment]
Yep, the `long` data type is 64-bit.

**Comment by MarkCallow** [comment]
Are you saying a jByteArray can't have more than 2^32 elements? Textures > 4GB are likely to be rare but they aren't non-existent. That and future-proofing are why the KTX spec uses 64-bit sizes.

I rather have the wrapper return error conditions to prevent creating or opening such large textures rather than casting and hiding the issue. Please amend the PR.

**Comment by ShukantPal** [comment]
> Are you saying a jByteArray can't have more than 2^32 elements?

Yes.

> I rather have the wrapper return error conditions to prevent creating or opening such large textures rather than casting and hiding the issue.

The issue is when copying image data into Java memory. I could make it so that it returns `null` when the data size is too large.

You could still work with images larger than 4GB though, and it doesn't make sense to restrict that use case; for example, someone might want to run the ASTC or Basis super compression algorithms on the texture - which run in libktx.

Also, I don't know how you'd prevent opening these large textures - you'd have to read the file separately and check the file size before passing it to libktx?

**Comment by MarkCallow** [comment]
> The issue is when copying image data into Java memory. I could make it so that it returns null when the data size is too large.

That works. Please make it so.

B.t.w we recently added a `perceptual` parameter to the ktxAstcParams struct. Please add it to KtxAstcParams.java too. Also please remove `separateRGToRGB_A` from KtxBasisParams.java. This has been deprecated and is a nop. Since we haven't yet released the Java wrapper I prefer to remove it now.

**Comment by ShukantPal** [comment]
@MarkCallow Done.
