### ISSUE TITLE
Incompatibility  of lib KTX with old GLIBC (glibc 2.17 Centos)

### ISSUE THREAD

**Issue by hbcodeXCI** [KhronosGroup/KTX-Software#552]
Hello,

I'am trying to build libktx in old CentOS (version 7.9 with glibc 2.17) but in the runtime I have a problem when I try to call any method (crash).

So What is the minimum required GLIBC to use with libktx (I did not find this information) because when I tried with ubuntu 18.04 (GlibC 2.27 I did not have this problem).

Thanks

**Comment by MarkCallow** [comment]
> So What is the minimum required GLIBC to use with libktx

I don't know the answer to that. It's a long time since we used anything earlier than Ubuntu 18.04. I was using successfully using Ubuntu Xenial (16.04) when I first embarked on version 4. Our CI builds currently use Focal (20.04) but the main reason for that is needing a minimum of CMake 3.16.

What kind of crash are you seeing?

**Comment by MarkCallow** [comment]
Closing as "won't fix". Reopen if you need a fix and be sure to provide more information about the crash.
