### ISSUE TITLE
Something appears to be wrong with how the PATH is set when installing KTX 4.0.0

### ISSUE THREAD

**Issue by kitaedesigns** [KhronosGroup/KTX-Software#580]
Have installed KTX 4.0.0 using the windows 64 bit installer (KTX-Software-4.0.0-win64) multiple times now, setting PATH for all users on this machine and using gltf-transform to encode ktx textures returns 

"error: Cannot convert undefined or null to object"

running "toktx --version" returns

'"toktx' is not recognized as an internal or external command,
operable program or batch file."

also tried compressing using ktx with gltfpack which returns the error

"Error: toktx is not present in PATH or TOKTX_PATH is not set
Note: toktx must be installed manually from https://github.com/KhronosGroup/KTX-Software/releases"

**Comment by MarkCallow** [comment]
I have had persistent problems with the installer reporting it was unable to add to PATH because the new PATH would exceed the maximum permitted length. Did you notice any such message when you were installing?

The error was bogus in my case. There was enough room in my %PATH%, by a few tens of bytes. I was able to to get it to add to %PATH% for the current user. Other users have reported no problems. It's worked for me on a different Windows box too. The second one had a much shorter %PATH%.

Adding for current user is one workaround. The other is to manually add the location to %PATH% via the Windows control panel.

This is an issue with the NullSoft Installer software. There has been no update to it since we made the installer you used so the issue will remain in future releases.

**Comment by kitaedesigns** [comment]
There was no notification that the PATH was unaccepted, it appeared as if everything installed correctly. I will try adding for current user and see if that resolves the issue. People with similar issues installing KTX albeit with gltfpacker and not gltf-transform mention the PATH containing spaces and requiring quotes that was throwing an error. https://github.com/zeux/meshoptimizer/discussions/247

**Comment by MarkCallow** [comment]
The default install location is `C:\Program Files\KTX-Software` so any shell command that attempts to add `C:\Program Files\KTX-Software\bin` to %PATH% needs to quote the string or escape the space character. The issue you point at was meshoptimizer not doing this. I'm near certain the installer is handling the space correctly. As I noted, it has worked for me on a machine with a short %PATH%.

Let me know what happens when you try adding for the current user. Also how close is your %PATH% length to 2048 characters?

**Comment by FireDragonGameStudio** [comment]
I encounter the same problem with the installer, not being able to set the %PATH% var correctly, although my install path is '''C:\Program Files\KTX-Software'''...

**Comment by FireDragonGameStudio** [comment]
Unfortunately there was no warning/error besides "could not set path variable". I just added the path environment variable to the bin directory manually and now everything seems working fine. :)

**Comment by ignarmezh** [comment]
> Unfortunately there was no warning/error besides "could not set path variable". I just added the path environment variable to the bin directory manually and now everything seems working fine. :)

What name and value you settled in environment variable?

**Comment by MarkCallow** [comment]
> What name and value you settled in environment variable?

As noted in [an earlier comment](https://github.com/KhronosGroup/KTX-Software/issues/580#issuecomment-1139504895) you have to add `C:\Program Files\KTX-Software\bin` (assuming you installed to the default location) to your `PATH` environment variable.

**Comment by ignarmezh** [comment]
> > What name and value you settled in environment variable?
> 
> As noted in [an earlier comment](https://github.com/KhronosGroup/KTX-Software/issues/580#issuecomment-1139504895) you have to add `C:\Program Files\KTX-Software\bin` (assuming you installed to the default location) to your `PATH` environment variable.

![image](https://github.com/KhronosGroup/KTX-Software/assets/20277993/808f62eb-d750-4f2c-9324-59349992ab9d)
Like this?

**Comment by MarkCallow** [comment]
> ![image](https://user-images.githubusercontent.com/20277993/268917515-808f62eb-d750-4f2c-9324-59349992ab9d.png) Like this?

Yes but if there were other folders already in PATH you should append `C:\Program Files\KTX-Software\bin` to it not replace everything. If this is the system PATH and you've replaced everything you will break a lot of other programs? If it is the current user's PATH you might get away with it without breaking too much.
