### ISSUE TITLE
ktxsc: fails with `Invalid cross-device link`

### ISSUE THREAD

**Issue by expenses** [KhronosGroup/KTX-Software#581]
When trying to run `ktxsc`, I get the following error:
```
ktxsc: rename of "%s" to "%s" failed: Invalid cross-device link
```
This appears to be caused by the `_trename` call failing:
https://github.com/KhronosGroup/KTX-Software/blob/bb9babcb8aa5711410c770fea1eb29d3febf04af/tools/ktxsc/ktxsc.cpp#L345-L349

**Comment by MarkCallow** [comment]
It looks like the file you are trying to supercompress is on a different device from where mktemp creates temporary files therefore rename/move can't work. To confirm this analysis please tell me your OS, the location of the file you were trying to supercompress and the value of your TMPDIR environment variable, if any.

**Comment by MarkCallow** [comment]
Please answer the questions I asked.

**Comment by MarkCallow** [comment]
> a) ktxsc shouldn't be trying to create temporary files at all. It can just write directly to the output file.

It only does this when overwriting the input. I did it because (1) I wanted to avoid having to read the entire file into memory and (2) I wanted to be able to leave the input file untouched if something goes wrong during the encoding. Turns out I'm reading the whole file anyway but 2 is still a valid reason.
