### ISSUE TITLE
Exposing whether an image is linear or uses sRGB

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/KTX-Software#604]
When selecting which transcode format to use based on the formats supported by the GPU, it would be useful to know the colour space used in an image. For a given compression scheme, the hardware might only support linear variants but not the sRGB one, in which case the application might want to choose another transcode format.

```c++
uint32_t* BDB = This->pDfd + 1;
const bool srgb = (KHR_DFDVAL(BDB, TRANSFER) == KHR_DF_TRANSFER_SRGB);
```
is what is used in lib/basis_transcode.cpp and `pDfd` is accessible to the user, but all the macros used afterwards are not.

Maybe libktx could expose a function `ktxTexture_GetColorSpace()` that, for now, would only return Linear or sRGB, but could be extended in the future with, for example, Rec. 2100 for HDR.

**Comment by MarkCallow** [comment]
The macros are defined in `KHR/khr_df.h` which can be downloaded from the Khronos [Data Format Spec. registry](https://registry.khronos.org/DataFormat/).

 It is also included in the GitHub [dfdutils repo](https://github.com/KhronosGroup/dfdutils) which is what is used by KTX-Software.

Even if we were to add a query, the result would use the KHR_DF_TRANSFER* definitions.

**Comment by MarkCallow** [comment]
Are you aware of any GPU that supports the sRGB variants of some compression scheme it supports but not the sRGB variants of another scheme?

One reason the query does not exist is because the transcoder pays attention to the color space of the data and chooses the output variant accordingly rendering it unnecessary in most cases. (There is no actual difference in the transcode operation. Only the VkFormat enum of the result changes.)

**Comment by lexaknyazev** [comment]
> Are you aware of any GPU that supports the sRGB variants of some compression scheme it supports but not the sRGB variants of another scheme?

There are a few examples:
- `GL_OES_compressed_ETC1_RGB8_texture` for OpenGL ES 2.0 does not provide an ETC1 sRGB enum. On some platforms, `GL_NV_sRGB_formats` fills that gap.
- PVRTC1/2 extensions on their own do not provide sRGB enums, a separate `GL_EXT_pvrtc_sRGB` is required for that. Because of this split, WebGL does not support PVRTC1 sRGB.
- S3TC sRGB formats are also not provided in the same GL extensions as linear S3TC formats.

Nevertheless, none of these matter for KTX 2.0 because it uses Vulkan enums that cover everything.

**Comment by MarkCallow** [comment]
The extension organization reflects the capabilities of different GPUs. I am asking for examples of a single GPU that supports sRGB for some schemes but not for others. For example a GPU that supports ETC2 and ASTC but only supports sRGB for ETC2 or vice-versa. The requested query seems more useful for deciding to use or not to use an sRGB texture rather than choosing a transcode target.

**Comment by lexaknyazev** [comment]
> I am asking for examples of a single GPU that supports sRGB for some schemes but not for others.

If uncompressed formats are included, then the first example fits this definition. Many OpenGL ES 2.0 GPUs support `GL_EXT_sRGB` and `GL_OES_compressed_ETC1_RGB8_texture` but not `GL_NV_sRGB_formats`. Therefore, an application may prefer an uncompressed format with hardware sRGB filtering instead of compressed format with slightly incorrect software sRGB filtering.

Devices with ETC2 and/or ASTC always support sRGB variants.

**Comment by pierremoreau** [comment]
> Are you aware of any GPU that supports the sRGB variants of some compression scheme it supports but not the sRGB variants of another scheme?

I have encountered a driver which exposes sRGB for ETC2 but not for S3TC for a given GPU. Though, the hardware seems to support sRGB for both formats so it could be considered to be more of a driver bug.

> If we were to add a query, the result would use the KHR_DF_TRANSFER* definitions so you'd still need the header.

Though in such a case, the dfd header would need to included from ktx.h and exposed as part of the library rather than having the user needing to provide their own copy of the header.

**Comment by lexaknyazev** [comment]
> I have encountered a driver which exposes sRGB for ETC2 but not for S3TC for a given GPU. 

Interesting! What API is being used and how do you check for sRGB support?

**Comment by pierremoreau** [comment]
> Interesting! What API is being used and how do you check for sRGB support?

I was looking at the tokens returned by `glGetIntergerv(GL_COMPRESSED_TEXTURE_FORMATS, …)`. With OpenGL it might not return all supported formats and got deprecated in 4.2 as a result (and one should instead just look at the exposed extensions, from what I understand). However with OpenGL ES it should be returning all supported formats and has not been deprecated.

**Comment by MarkCallow** [comment]
There is already a function for this: `ktxtexture2_GetOETF`. Sorry I didn't remember this earlier. It returns a KHR_DF_TRANSFER value so you will need the `KHR/khr_df.h` header file for readable tokens mapped to the values.

**Comment by pierremoreau** [comment]
Ah indeed, thanks for pointing it out!
It’s a bit unfortunate that a separate dependency is needed to interpret the output of that function.

**Comment by MarkCallow** [comment]
I'll probably add `KHR/khr_df.h` to the installers in a post 4.1.0 release.
