### ISSUE TITLE
Can't use stdin instead of infile.

### ISSUE THREAD

**Issue by GRAPHENE9932** [KhronosGroup/KTX-Software#637]
This command:
`./toktx photo_1.ktx2 < photo_1.jpg`
outputs:
```
toktx: need some input files.
Usage: toktx [options] <outfile> [<infile>.{pam,pgm,ppm} ...]

  <outfile>    The destination ktx file. ".ktx" will appended if necessary.
               If it is '-' the output will be written to stdout.
  <infile>     One or more image files in .jpg, .png, .pam, .ppm, or .pgm
               format. Other formats can be readily converted to these formats
               using tools such as ImageMagick and XnView. When no infile is
               specified, stdin is used. infiles prefixed with '@' are read as
               text files listing actual file names to process with one file
               path per line. Paths must be absolute or relative to the current
               directory when toktx is run. If '@@' is used instead, paths must
               be absolute or relative to the location of the list file.
*help text continues...*
```
infile is not specified, so toktx must use stdin, but it's not.

I reproduced this on version 4.0.0 (.tar.bz archive with Linux binaries from releases page) and on version I compiled myself from master.

**Comment by MarkCallow** [comment]
This was principally a documentation issue. The `--help` doc was wrong. The man page was correct. The referenced commit fixes the documentation.

Using stdin is a difficult problem to solve. Because several formats are supported and each needs to be tried we have to be able to rewind the input. On most systems this will mean reading the entire content from stdin into memory. As it is only possible to support a single input file via stdin, the feature could be used in only a subset of cases so I do not view it as essential.

In the background I am rewriting the image input part of toktx to make it easier to add additional formats. In the process I am attempting to add stdin support.
