### ISSUE TITLE
Conflicting linkage error when building some unit tests with TDM-GCC-64

### ISSUE THREAD

**Issue by ltqsoft** [KhronosGroup/KTX-Software#640]
Tests:
1. [unittests/image_unittests.cc](https://github.com/KhronosGroup/KTX-Software/blob/master/tests/unittests/image_unittests.cc)
2. [unittests/unittests.cc](https://github.com/KhronosGroup/KTX-Software/blob/master/tests/unittests/unittests.cc)
3. [texturetests/texturetests.cc](https://github.com/KhronosGroup/KTX-Software/blob/master/tests/texturetests/texturetests.cc)

On my machine, It looks like I fixed this by replacing each line21 of those with:
`#if (_MSC_VER < 1900) && !defined(__GNUC__)`

[unittests/image_unittests.cc#L21](https://github.com/KhronosGroup/KTX-Software/blob/master/tests/unittests/image_unittests.cc#L21)
[unittests/unittests.cc#L21](https://github.com/KhronosGroup/KTX-Software/blob/master/tests/unittests/unittests.cc#L21)
[texturetests/texturetests.cc#L21](https://github.com/KhronosGroup/KTX-Software/blob/master/tests/texturetests/texturetests.cc#L21)

TDM-GCC-64 version: 10.3.0

**Comment by MarkCallow** [comment]
I am worried that this will screw up the Mingw build, which is currently working fine, since it also defines __GNUC__.

If you want this to progress then please submit a PR so all the builds will be checked and, if the Mingw build breaks, you can figure out a fix. Please note that as a 1st time contributor I will have to authorize the GitHub Actions build, which is where the MingW build happens. There may be a delay before I see the PR and can authorize.

What is TDM-GCC?

**Comment by ltqsoft** [comment]
It looks like the problem came from CMake, The erros are gone after I downloaded the latest version. Let's close this issue.
