### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/KTX-Software#670]
Would you like to add more error handling for return values from functions like the following?
* [fprintf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output.") ⇒ [printKTX2Info2](https://github.com/KhronosGroup/KTX-Software/blob/784ed9acefd6dc29c521dc76f7297ff2e28c8d7a/lib/info.c#L373)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [writeHeader](https://github.com/KhronosGroup/KTX-Software/blob/e4bf1aaac57cbcb90b2b6e876c41218a8972a566/lib/dfdutils/createdfd.c#L25)
* [puts](https://pubs.opengroup.org/onlinepubs/9699919799/functions/puts.html "Put a string on standard output.") ⇒ [print_usage](https://github.com/KhronosGroup/KTX-Software/blob/c65cfd0d0dc39836ee4bcf56404ec2dcb86cef3b/lib/basisu/basisu_tool.cpp#L61)

**Comment by MarkCallow** [comment]
What is this phrased as a question? Are you selling some kind of tool?

There have been major rewrites of a lot of the code where the first 2 bullets are located. The 3rd refers to code that is not used in this project. Closing.

**Comment by MarkCallow** [comment]
> 👀 [Some update candidates were left over](https://github.com/KhronosGroup/KTX-Software/blob/e724f180d932b8fa5512109265a22de7f550f49c/lib/info.c#L373), weren't they?

Not all the rewrites are in `main` yet including `info.c`. It has been largely rewritten with new functionality. It is a work in progress in the `ktxtools` branch. Once it is merged to `main` please take a look again. Don't spend any time on it now because there will be further changes before then and it likely has still has warnings on some platforms.

> 💭 Can you adhere to [secure programming guidelines](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions)?

Yes.

> Can the status be clarified any further for such a software component in this repository? 🤔

basis_tool.cpp is part of another repo that is included via `git subrepo`. It is a command line tool that is not used by KTX-Software and not included in the list of sources compiled by KTX-Software. How and where do you suggest I clarify the status?

**Comment by elfring** [comment]
* :thinking: How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?
