### ISSUE TITLE
How to compile on Windows?

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/KTX-Software#679]
I'm trying to make a debug build of `libKTX` so I can debug why I'm getting `KTX_INVALID_OPERATION` when uploading a texture to Vulkan

I've added it to my CMake file as so
```cmake
FetchContent_Declare(
        fetch_libktx
        GIT_REPOSITORY  https://github.com/KhronosGroup/KTX-Software.git
        GIT_TAG         v4.1.0-rc3
)
FetchContent_MakeAvailable(fetch_libktx)
```
However, when I try to build my project, I get an error
```
4>CMake Error at D:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
4>  Could NOT find Bash (missing: BASH_EXECUTABLE)
4>Call Stack (most recent call first):
4>  D:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
4>  build/_deps/fetch_libktx-src/cmake/modules/FindBash.cmake:96 (find_package_handle_standard_args)
4>  build/_deps/fetch_libktx-src/CMakeLists.txt:8 (find_package)
```

I'm using CMake 3.23.2 and Visual Studio 2022 version 17.5.1. I don't understand why `libKTX` is trying to find Bash when I'm on Windows

What's the best path forward here? Can I edit the `libKTX` CMake file to not try to use Bash on Windows?

**Comment by MarkCallow** [comment]
See https://github.com/KhronosGroup/KTX-Software/blob/main/BUILDING.md#windows and look for "A bash shell". You may also be interested in the following closed issues: #379, #405 and #572.

Many developers use Git for Windows which includes Bash so we haven't felt a need to make a duplicate PowerShell version of the script. However now that the version script is stable and rarely changed, I would accept a PR that provides a PowerShell version of the script for use on Windows and changes to the CMake build to use that instead of Bash on Windows.

We aren't planning to do this ourselves so I will close this issue.
