### ISSUE TITLE
misleading-indentation error when compiling with mingw64

### ISSUE THREAD

**Issue by viseztrance** [KhronosGroup/KTX-Software#709]
When compiling with mingw64, I get the following error:

```
/home/daniel/Projects/aurora/vendor/KTX-Software/lib/filestream.c: In function 'ktxFileStream_getsize':
/home/daniel/Projects/aurora/vendor/KTX-Software/lib/filestream.c:316:3: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
  316 |   if (str->data.file->_flag & _IOWRT)
      |   ^~
/home/daniel/Projects/aurora/vendor/KTX-Software/lib/filestream.c:319:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
  319 |     statret = fstat(fileno(str->data.file), &statbuf);
      |     ^~~~~~~
```

Version used:
```sh
x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (GCC) 12.2.1 20221121 (Fedora MinGW 12.2.1-8.fc38)
```

Currently I'm using `-DCMAKE_C_FLAGS="-Wno-error=misleading-indentation"` as a workaround, but thought I would let you know about this issue.

**Comment by MarkCallow** [comment]
We have a MinGW build in our CI that succeeds. (We have warnings as errors set). It is using GCC 12.2.0. I wonder if they "improved" the misleading indentation detection in 12.2.1. Indentation is the way it is because the `if` is inside an `#ifdef`. Code is correct. Only the `fflush` is intended to be guarded by the `if`.

**Comment by MarkCallow** [comment]
In our MinGW CI build the `#if` is never true because `_UCRT` is defined. That means the MingGW we are using uses the new C run-time library as indicated by _UCRT not the old buggy one. Therefore the compiler does not have any cause to raise this warning.

I find it strange that you have a version of MinGW with a compiler version recent enough to have the misleading indentation warning yet still using the old CRT.
