### ISSUE TITLE
No longer compiles with Clang 20

### ISSUE THREAD

**Issue by Cons-Cat** [KhronosGroup/KTX-Software#955]
The development version of Clang 20 recently added a warning for the combination of `-ffp-model` with `-ffp-contract`, and portions of libktx have a non-configurable `-Werror,-Woverriding-option` which retroactively makes it impossible to compile this way. These flags can be slightly changed with the `ASTCENC_INVARIANCE` CMake variable, but afaik there is no configuration which avoids the error entirely.

Example of the new issue with these flags:
https://godbolt.org/z/qo6jEYrc4

**Comment by MarkCallow** [comment]
This was fixed by PR #933 on Sep. 6th which globally sets `-Wno-overriding-option` for Clang 20+. Have you pulled the latest code?

I do not know where the `-Woverriding-option` you see is coming from. It has not been added to any of our CMake files. Please provide more information of what portions of libktx have this. Are you sure it part of libktx where you see this rather than some other part of KTX-Software?

`-Werror` is not set by default. To set it you need to set KTX_WERROR=ON when configuring your build. We set it in all our CI builds, some of which are using Clang 20, and they all pass so `-Wno-overriding-option` is doing its job,

**Comment by MarkCallow** [comment]
I refer you to https://github.com/ARM-software/astc-encoder/issues/499#issuecomment-2309930326 for our opinion on the, er, usefulness of this new warning.

**Comment by MarkCallow** [comment]
Closing. This was fixed. I believe the reporter was not using the top of trunk. Reopen if something else is going on.
