### ISSUE TITLE
How can I make a KTX if no software supports it?

### ISSUE THREAD

**Issue by pheonixfirewingz** [KhronosGroup/KTX-Software#963]
I wanted to use KTX for my game framework but I can't find a image editor that supports the format can you point me to one that works on Linux.

**Comment by MarkCallow** [comment]
Image editors are not the best place for KTX support. This is because many files, including ones you are using per #965, use images that are in block-compressed formats. Decoding, editing and re-encoding such images will introduce artifacts, worsening each time. For best results you need to edit the original uncompressed image and encode that modified image.

It would make sense for an editor that is designed creating textures with multiple images, such as array, cube map and mip-mapped textures, to support KTX as it can store each of these types in a single file. If it has support for making compressed textures, it should arrange to always keep an uncompressed KTX file for future editing and treat the compressed file as an exported item. I am not aware of any such editors. I'd love to see some.

For 2D textures you can keep your original single image in PNG or EXR files and use `ktx create` to make the KTX file, including encoding to block-compressed formats. `ktx create` can also generate your mipmap images. 

You might want to look at [Compressonator](https://github.com/GPUOpen-Tools/compressonator#compressonator), from AMD’s GPUOpen initiative or [NVIDIA Texture Tools Exporter](https://developer.nvidia.com/nvidia-texture-tools-exporter). The latter is available as a standalone GUI tool or a Photoshop Plugin. It supports loading from KTX1 and KTX2 textures and can export to KTX2. If you are using the plugin version you can presumably use Photoshop for editing images. I do not know if you can do image editing in Compressonator or the standalone GUI version of NVIDIA's tool.
