### ISSUE TITLE
HELP! OpenglLoader TODO making it Impossible to load ktx2 file to opengl!

### ISSUE THREAD

**Issue by pheonixfirewingz** [KhronosGroup/KTX-Software#965]
the code in the [glloader line 1024](https://github.com/KhronosGroup/KTX-Software/blob/c16537c89aef25980aa1ed56b5bd371619e1ed11/lib/glloader.c#L1024) has a TODO in it that when i'm trying to use the loader catches here I Don't Know how to fix this as I don't understand how it works to start writing the code to fix this could someone help me here.

**Comment by MarkCallow** [comment]
Please run `ktx info` on the file you are trying to load and post the output here. (The `ktx` tool is one of the tools in packages you can find in this project's [Releases](https://github.com/KhronosGroup/KTX-Software/releases.)

I suspect you are trying to load a KTX file whose payload is Basis Universal encoded which, as the comment next to the return statement says, must be transcoded to a format supported by the local GPU before it can be uploaded. I'm not aware of any other cases currently in use where the vkFormat field is `VK_FORMAT_UNDEFINED`. (The TODO comment is out of date and misleading. ASTC HDR and 3D now have VkFormat enum values.  For any other cases the loader should look for metadata giving the glInternalFormat to use.

**Comment by pheonixfirewingz** [comment]
I hope this info helps @MarkCallow most of this I'm just trying to get KTX support in my OpenGL es 3.2 renderer I don't understand the KTX format well. I know it will be a pain when I port the texture code to the other APIs dx12, Vulkan 1.2(Not So Much) & metal.
command used to make the file `toktx --verbose --encode uastc --uastc_quality 2 --assign_oetf srgb --2d --t2 --target_type RGBA --genmipmap input.ktx2 input.png`
the version `toktx -v toktx v4.3.2`
**KTX info output**
 Validation successful

Header

identifier: «KTX 20»\r\n\x1A\n
vkFormat: VK_FORMAT_UNDEFINED
typeSize: 1
pixelWidth: 1920
pixelHeight: 1080
pixelDepth: 0
layerCount: 0
faceCount: 1
levelCount: 11
supercompressionScheme: KTX_SS_NONE
dataFormatDescriptor.byteOffset: 0x158
dataFormatDescriptor.byteLength: 44
keyValueData.byteOffset: 0x184
keyValueData.byteLength: 124
supercompressionGlobalData.byteOffset: 0
supercompressionGlobalData.byteLength: 0

Level Index

Level0.byteOffset: 0xa9390
Level0.byteLength: 2073600
Level0.uncompressedByteLength: 2073600
Level1.byteOffset: 0x2aa90
Level1.byteLength: 518400
Level1.uncompressedByteLength: 518400
Level2.byteOffset: 0xac90
Level2.byteLength: 130560
Level2.uncompressedByteLength: 130560
Level3.byteOffset: 0x2d10
Level3.byteLength: 32640
Level3.uncompressedByteLength: 32640
Level4.byteOffset: 0xd30
Level4.byteLength: 8160
Level4.uncompressedByteLength: 8160
Level5.byteOffset: 0x4c0
Level5.byteLength: 2160
Level5.uncompressedByteLength: 2160
Level6.byteOffset: 0x2c0
Level6.byteLength: 512
Level6.uncompressedByteLength: 512
Level7.byteOffset: 0x240
Level7.byteLength: 128
Level7.uncompressedByteLength: 128
Level8.byteOffset: 0x220
Level8.byteLength: 32
Level8.uncompressedByteLength: 32
Level9.byteOffset: 0x210
Level9.byteLength: 16
Level9.uncompressedByteLength: 16
Level10.byteOffset: 0x200
Level10.byteLength: 16
Level10.uncompressedByteLength: 16

Data Format Descriptor

DFD total bytes: 44
Vendor ID: KHR_DF_VENDORID_KHRONOS
Descriptor type: KHR_DF_KHR_DESCRIPTORTYPE_BASICFORMAT
Version: KHR_DF_VERSIONNUMBER_1_3
Descriptor block size: 40
Flags: 0x0 (KHR_DF_FLAG_ALPHA_STRAIGHT)
Transfer: KHR_DF_TRANSFER_SRGB
Primaries: KHR_DF_PRIMARIES_BT709
Model: KHR_DF_MODEL_UASTC
Dimensions: 4, 4, 1, 1
Plane bytes: 16, 0, 0, 0, 0, 0, 0, 0
Sample 0:
    Qualifiers: 0x0 ()
    Channel Type: 0x0 (KHR_DF_CHANNEL_UASTC_RGB)
    Length: 128 bits Offset: 0
    Position: 0, 0, 0, 0
    Lower: 0x00000000
    Upper: 0xffffffff

Key/Value Data

KTXorientation: rd
KTXwriter: toktx v4.3.2 / libktx v4.3.2
KTXwriterScParams: --encode uastc --uastc_quality 2

**Comment by MarkCallow** [comment]
As I suspected you are trying to load a Basis Universal format texture, in this case UASTC (colorModel `KHR_DF_MODEL_UASTC`). You need to transcode this to a format supported on the local GPU such as ASTC or BC7. First call `ktxTexture2_TranscodeBasis` to do this then call `ktxTexture2_GLUpload`. You can call `ktxTexture_NeedsTranscoding` to see if it is necessary to call `ktxTexture2_TranscodeBasis`. See [DrawTexture.cpp](https://github.com/KhronosGroup/KTX-Software/blob/main/tests/loadtests/glloadtests/shader-based/DrawTexture.cpp) and [GLTextureTranscoder.hpp](https://github.com/KhronosGroup/KTX-Software/blob/main/tests/loadtests/glloadtests/utils/GLTextureTranscoder.hpp) for example code.

Transcoding is not done automatically because the choice of transcode target is best left to the application.

> I know it will be a pain when I port the texture code to the other APIs dx12, Vulkan 1.2(Not So Much) & metal.

The pain does not come from the KTX format. It is from having to write different code for those other APIs. While _libktx_ has a loader for Vulkan, you will have to write loaders for dx12 and Metal. We have open issues seeking volunteers to implement those loaders.

Since you are using a universal format one part of the potential pain is solved. You can transcode to whatever format the GPU and API supports. Metal on Apple Silicon supports ASTC. On DX12 you'll have to use BC7 as your transcode target. Note that while Apple Silicon supports ASTC, the ASTC extension is not exposed in OpenGL or WebGL on macOS so you can't use it in those APIs. It is exposed in Vulkan/MoltenVK. Many Intel integrated GPUs support also ASTC but I do not think it is exposed in DX12. Could be wrong.
